### ISSUE TITLE
Trying to sync with framabag

### ISSUE THREAD

**Issue by clrh** [yurumi/harbour-sailabag#18]
Hi,

I am trying to sync with http://framabag.org/u/

The app tells me "success database synchronised" but I got no article to view...

I put usename, pass, server, token and id.

An idea ?

Thanks...

**Comment by nicosomb** [comment]
Hello @clrh! 

Are you sure that you configure the correct URL? Your URL must be framabag.org/u/your_pseudo.

**Comment by clrh** [comment]
Hi, this issue is no longer pertinent. So, I close, sorry.
